### ISSUE TITLE
Prepare next patch release

### ISSUE THREAD

**Issue by tute** [thoughtbot/fake_stripe#66] opened 2016-12-01 01:35 UTC
An application I'm working on needs the following commit:

https://github.com/thoughtbot/fake_stripe/commit/e4f98adc4795a264601860e28c762d02a4952764

I now tie its Gemfile to the `master` branch for now, but I plan to release v0.0.11 from latest master.

I announce this here in case you have any feedback before I do so. Thank you!

cc @gylaz: can you please add me as an owner in rubygems? You could also release it yourself if you prefer. Thank you!

**Comment by naw** [comment] 2016-12-01 01:41
I think it would be prudent to address https://github.com/thoughtbot/fake_stripe/issues/60 before you do a release. Currently the problem is in `master`, but not in the latest release.

cc @seanpdoyle

**Comment by tute** [comment] 2017-03-09 12:47
#60 has been released. 🎉 

Can we prepare a next release, please? Thank you!

**Comment by stefannibrasil** [comment] 2024-09-19 23:22
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154

**Closed by stefannibrasil** 2024-09-19 23:22 UTC
